name: auto-green

# on:
#   push:
#     branches:
#       - master
#   schedule:
#     - cron: "0 0 * * *"
#   workflow_dispatch:

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: auto green
        run: |
          git config --local user.email "iamazy.me@outlook.com"
          git config --local user.name "iamazy"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "a commit a day keeps your girlfriend away"
          git push
